replicas: 1

image: "docker.elastic.co/logstash/logstash"
imageTag: "7.16.2"

logstashJavaOpts: "-Xmx512m -Xms512m"

resources:
  requests:
    cpu: "500m"
    memory: "1536Mi"
  limits:
    cpu: "1000m"
    memory: "1536Mi"

service:
  annotations: {}
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

logstashConfig:
  logstash.yml: |
    pipeline.ecs_compatibility: disabled
    http.host: 0.0.0.0

logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      if [kubernetes] {
        if [kubernetes][labels][app][value] {
          mutate { add_field => { "[@metadata][app_name]" => "%{[kubernetes][labels][app][value]}" } }
        } else {
          mutate { add_field => { "[@metadata][app_name]" => "%{[kubernetes][labels][app]}" } }
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://host.docker.internal:9200"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}"
      }
    }