apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vroong-devopstest
spec:
  rules:
    - host: null
      http:
        paths:
          - backend:
              service:
                name: vroong-devopstest
                port:
                  number: 80
            path: /*
            pathType: ImplementationSpecific
